"""
    OpenAPI pytorch-vc-heroku-flask

    This is a simple server presenting voice conversion powered with pytorch and flask. For this sample, you can use the api key `special-key` to test the authorization filters.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.vc_api import VcApi  # noqa: E501


class TestVcApi(unittest.TestCase):
    """VcApi unit test stubs"""

    def setUp(self):
        self.api = VcApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_upload_file_get(self):
        """Test case for upload_file_get

        Load main page  # noqa: E501
        """
        pass

    def test_upload_file_post(self):
        """Test case for upload_file_post

        Upload source and target  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
